// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3sxa0kTwx-KvGOYv9jyxVTmmq5Q6GKcE',
    appId: '1:532125817379:web:3ddf46a0c3f05b965d6f96',
    messagingSenderId: '532125817379',
    projectId: 'myhx-app',
    authDomain: 'myhx-app.firebaseapp.com',
    storageBucket: 'myhx-app.firebasestorage.app',
    measurementId: 'G-TFJHY5KNSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQAKoGYwOjp6L7Db2DGFfieMAHlS8gsMw',
    appId: '1:532125817379:android:7ccf4d6c392584fc5d6f96',
    messagingSenderId: '532125817379',
    projectId: 'myhx-app',
    storageBucket: 'myhx-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE_xC3d-WaKGeTIhQCqcP5dq8t7ftdIr4',
    appId: '1:532125817379:ios:ef3cec407ec961945d6f96',
    messagingSenderId: '532125817379',
    projectId: 'myhx-app',
    storageBucket: 'myhx-app.firebasestorage.app',
    iosClientId: '532125817379-dds2dlucs4hmhqqs7aps487ov4dg80ip.apps.googleusercontent.com',
    iosBundleId: 'com.example.myhxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE_xC3d-WaKGeTIhQCqcP5dq8t7ftdIr4',
    appId: '1:532125817379:ios:ef3cec407ec961945d6f96',
    messagingSenderId: '532125817379',
    projectId: 'myhx-app',
    storageBucket: 'myhx-app.firebasestorage.app',
    iosClientId: '532125817379-dds2dlucs4hmhqqs7aps487ov4dg80ip.apps.googleusercontent.com',
    iosBundleId: 'com.example.myhxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3sxa0kTwx-KvGOYv9jyxVTmmq5Q6GKcE',
    appId: '1:532125817379:web:f72639c7fd4a0f025d6f96',
    messagingSenderId: '532125817379',
    projectId: 'myhx-app',
    authDomain: 'myhx-app.firebaseapp.com',
    storageBucket: 'myhx-app.firebasestorage.app',
    measurementId: 'G-NWK0Z8H71K',
  );

}